# Generated by Django 5.2.5 on 2025-09-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('residente', 'Residente'), ('copropietario', 'Copropietario'), ('guardia', 'Guardia'), ('visitante', 'Visitante')], default='residente', max_length=20),
        ),
    ]
