# Generated by Django 5.2.5 on 2025-09-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_alter_administrador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={},
        ),
    ]
