# Generated by Django 5.2.5 on 2025-09-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copropietarios', '0001_initial'),
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='copropietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viviendas', to='copropietarios.copropietario'),
        ),
    ]
